(* auto-generated by gt *)

open Smtlib_syntax;;

let rec dummy () = () 
and eq_an_option = function 
   |AnOptionAttribute (_ , attribute1_1),AnOptionAttribute (_ , attribute1_2)-> true && eq_attribute(attribute1_1 , attribute1_2)
and eq_attribute = function 
   |AttributeKeyword (_ , str1_1),AttributeKeyword (_ , str1_2)-> true && str1_1 = str1_2
   |AttributeKeywordValue (_ , str1_1 , attributevalue2_1),AttributeKeywordValue (_ , str1_2 , attributevalue2_2)-> true && str1_1 = str1_2 && eq_attributevalue(attributevalue2_1 , attributevalue2_2)
   | _ -> false

and eq_attributevalue = function 
   |AttributeValSpecConst (_ , specconstant1_1),AttributeValSpecConst (_ , specconstant1_2)-> true && eq_specconstant(specconstant1_1 , specconstant1_2)
   |AttributeValSymbol (_ , symbol1_1),AttributeValSymbol (_ , symbol1_2)-> true && eq_symbol(symbol1_1 , symbol1_2)
   |AttributeValSexpr (_ , attributevalsexpr_attributevalue_sexpr52_1),AttributeValSexpr (_ , attributevalsexpr_attributevalue_sexpr52_2)-> true && eq_attributevalsexpr_attributevalue_sexpr5(attributevalsexpr_attributevalue_sexpr52_1 , attributevalsexpr_attributevalue_sexpr52_2)
   | _ -> false

and eq_command = function 
   |CommandSetLogic (_ , symbol3_1),CommandSetLogic (_ , symbol3_2)-> true && eq_symbol(symbol3_1 , symbol3_2)
   |CommandSetOption (_ , an_option3_1),CommandSetOption (_ , an_option3_2)-> true && eq_an_option(an_option3_1 , an_option3_2)
   |CommandSetInfo (_ , attribute3_1),CommandSetInfo (_ , attribute3_2)-> true && eq_attribute(attribute3_1 , attribute3_2)
   |CommandDeclareSort (_ , symbol3_1 , str4_1),CommandDeclareSort (_ , symbol3_2 , str4_2)-> true && eq_symbol(symbol3_1 , symbol3_2) && str4_1 = str4_2
   |CommandDefineSort (_ , symbol3_1 , commanddefinesort_command_symbol115_1 , sort7_1),CommandDefineSort (_ , symbol3_2 , commanddefinesort_command_symbol115_2 , sort7_2)-> true && eq_symbol(symbol3_1 , symbol3_2) && eq_commanddefinesort_command_symbol11(commanddefinesort_command_symbol115_1 , commanddefinesort_command_symbol115_2) && eq_sort(sort7_1 , sort7_2)
   |CommandDeclareFun (_ , symbol3_1 , commanddeclarefun_command_sort135_1 , sort7_1),CommandDeclareFun (_ , symbol3_2 , commanddeclarefun_command_sort135_2 , sort7_2)-> true && eq_symbol(symbol3_1 , symbol3_2) && eq_commanddeclarefun_command_sort13(commanddeclarefun_command_sort135_1 , commanddeclarefun_command_sort135_2) && eq_sort(sort7_1 , sort7_2)
   |CommandDefineFun (_ , symbol3_1 , commanddefinefun_command_sortedvar155_1 , sort7_1 , term8_1),CommandDefineFun (_ , symbol3_2 , commanddefinefun_command_sortedvar155_2 , sort7_2 , term8_2)-> true && eq_symbol(symbol3_1 , symbol3_2) && eq_commanddefinefun_command_sortedvar15(commanddefinefun_command_sortedvar155_1 , commanddefinefun_command_sortedvar155_2) && eq_sort(sort7_1 , sort7_2) && eq_term(term8_1 , term8_2)
   |CommandPush (_ , str3_1),CommandPush (_ , str3_2)-> true && str3_1 = str3_2
   |CommandPop (_ , str3_1),CommandPop (_ , str3_2)-> true && str3_1 = str3_2
   |CommandAssert (_ , term3_1),CommandAssert (_ , term3_2)-> true && eq_term(term3_1 , term3_2)
   |CommandCheckSat (_),CommandCheckSat (_)-> true
   |CommandGetAssert (_),CommandGetAssert (_)-> true
   |CommandGetProof (_),CommandGetProof (_)-> true
   |CommandGetUnsatCore (_),CommandGetUnsatCore (_)-> true
   |CommandGetValue (_ , commandgetvalue_command_term244_1),CommandGetValue (_ , commandgetvalue_command_term244_2)-> true && eq_commandgetvalue_command_term24(commandgetvalue_command_term244_1 , commandgetvalue_command_term244_2)
   |CommandGetAssign (_),CommandGetAssign (_)-> true
   |CommandGetOption (_ , str3_1),CommandGetOption (_ , str3_2)-> true && str3_1 = str3_2
   |CommandGetInfo (_ , infoflag3_1),CommandGetInfo (_ , infoflag3_2)-> true && eq_infoflag(infoflag3_1 , infoflag3_2)
   |CommandExit (_),CommandExit (_)-> true
   | _ -> false

and eq_commands = function 
   |Commands (_ , commands_commands_command301_1),Commands (_ , commands_commands_command301_2)-> true && eq_commands_commands_command30(commands_commands_command301_1 , commands_commands_command301_2)
and eq_identifier = function 
   |IdSymbol (_ , symbol1_1),IdSymbol (_ , symbol1_2)-> true && eq_symbol(symbol1_1 , symbol1_2)
   |IdUnderscoreSymNum (_ , symbol3_1 , idunderscoresymnum_identifier_numeral334_1),IdUnderscoreSymNum (_ , symbol3_2 , idunderscoresymnum_identifier_numeral334_2)-> true && eq_symbol(symbol3_1 , symbol3_2) && eq_idunderscoresymnum_identifier_numeral33(idunderscoresymnum_identifier_numeral334_1 , idunderscoresymnum_identifier_numeral334_2)
   | _ -> false

and eq_infoflag = function 
   |InfoFlagKeyword (_ , str1_1),InfoFlagKeyword (_ , str1_2)-> true && str1_1 = str1_2
and eq_qualidentifier = function 
   |QualIdentifierId (_ , identifier1_1),QualIdentifierId (_ , identifier1_2)-> true && eq_identifier(identifier1_1 , identifier1_2)
   |QualIdentifierAs (_ , identifier3_1 , sort4_1),QualIdentifierAs (_ , identifier3_2 , sort4_2)-> true && eq_identifier(identifier3_1 , identifier3_2) && eq_sort(sort4_1 , sort4_2)
   | _ -> false

and eq_sexpr = function 
   |SexprSpecConst (_ , specconstant1_1),SexprSpecConst (_ , specconstant1_2)-> true && eq_specconstant(specconstant1_1 , specconstant1_2)
   |SexprSymbol (_ , symbol1_1),SexprSymbol (_ , symbol1_2)-> true && eq_symbol(symbol1_1 , symbol1_2)
   |SexprKeyword (_ , str1_1),SexprKeyword (_ , str1_2)-> true && str1_1 = str1_2
   |SexprInParen (_ , sexprinparen_sexpr_sexpr412_1),SexprInParen (_ , sexprinparen_sexpr_sexpr412_2)-> true && eq_sexprinparen_sexpr_sexpr41(sexprinparen_sexpr_sexpr412_1 , sexprinparen_sexpr_sexpr412_2)
   | _ -> false

and eq_sort = function 
   |SortIdentifier (_ , identifier1_1),SortIdentifier (_ , identifier1_2)-> true && eq_identifier(identifier1_1 , identifier1_2)
   |SortIdSortMulti (_ , identifier2_1 , sortidsortmulti_sort_sort443_1),SortIdSortMulti (_ , identifier2_2 , sortidsortmulti_sort_sort443_2)-> true && eq_identifier(identifier2_1 , identifier2_2) && eq_sortidsortmulti_sort_sort44(sortidsortmulti_sort_sort443_1 , sortidsortmulti_sort_sort443_2)
   | _ -> false

and eq_sortedvar = function 
   |SortedVarSymSort (_ , symbol2_1 , sort3_1),SortedVarSymSort (_ , symbol2_2 , sort3_2)-> true && eq_symbol(symbol2_1 , symbol2_2) && eq_sort(sort3_1 , sort3_2)
and eq_specconstant = function 
   |SpecConstsDec (_ , str1_1),SpecConstsDec (_ , str1_2)-> true && str1_1 = str1_2
   |SpecConstNum (_ , str1_1),SpecConstNum (_ , str1_2)-> true && str1_1 = str1_2
   |SpecConstString (_ , str1_1),SpecConstString (_ , str1_2)-> true && str1_1 = str1_2
   |SpecConstsHex (_ , str1_1),SpecConstsHex (_ , str1_2)-> true && str1_1 = str1_2
   |SpecConstsBinary (_ , str1_1),SpecConstsBinary (_ , str1_2)-> true && str1_1 = str1_2
   | _ -> false

and eq_symbol = function 
   |Symbol (_ , str1_1),Symbol (_ , str1_2)-> true && str1_1 = str1_2
   |SymbolWithOr (_ , str1_1),SymbolWithOr (_ , str1_2)-> true && str1_1 = str1_2
   | _ -> false

and eq_term = function 
   |TermSpecConst (_ , specconstant1_1),TermSpecConst (_ , specconstant1_2)-> true && eq_specconstant(specconstant1_1 , specconstant1_2)
   |TermQualIdentifier (_ , qualidentifier1_1),TermQualIdentifier (_ , qualidentifier1_2)-> true && eq_qualidentifier(qualidentifier1_1 , qualidentifier1_2)
   |TermQualIdTerm (_ , qualidentifier2_1 , termqualidterm_term_term563_1),TermQualIdTerm (_ , qualidentifier2_2 , termqualidterm_term_term563_2)-> true && eq_qualidentifier(qualidentifier2_1 , qualidentifier2_2) && eq_termqualidterm_term_term56(termqualidterm_term_term563_1 , termqualidterm_term_term563_2)
   |TermLetTerm (_ , termletterm_term_varbinding584_1 , term6_1),TermLetTerm (_ , termletterm_term_varbinding584_2 , term6_2)-> true && eq_termletterm_term_varbinding58(termletterm_term_varbinding584_1 , termletterm_term_varbinding584_2) && eq_term(term6_1 , term6_2)
   |TermForAllTerm (_ , termforallterm_term_sortedvar604_1 , term6_1),TermForAllTerm (_ , termforallterm_term_sortedvar604_2 , term6_2)-> true && eq_termforallterm_term_sortedvar60(termforallterm_term_sortedvar604_1 , termforallterm_term_sortedvar604_2) && eq_term(term6_1 , term6_2)
   |TermExistsTerm (_ , termexiststerm_term_sortedvar624_1 , term6_1),TermExistsTerm (_ , termexiststerm_term_sortedvar624_2 , term6_2)-> true && eq_termexiststerm_term_sortedvar62(termexiststerm_term_sortedvar624_1 , termexiststerm_term_sortedvar624_2) && eq_term(term6_1 , term6_2)
   |TermExclimationPt (_ , term3_1 , termexclimationpt_term_attribute644_1),TermExclimationPt (_ , term3_2 , termexclimationpt_term_attribute644_2)-> true && eq_term(term3_1 , term3_2) && eq_termexclimationpt_term_attribute64(termexclimationpt_term_attribute644_1 , termexclimationpt_term_attribute644_2)
   | _ -> false

and eq_varbinding = function 
   |VarBindingSymTerm (_ , symbol2_1 , term3_1),VarBindingSymTerm (_ , symbol2_2 , term3_2)-> true && eq_symbol(symbol2_1 , symbol2_2) && eq_term(term3_1 , term3_2)
and eq_termexclimationpt_term_attribute64 = function 
   |(_,[]),(_,[])-> true
   | (d , (attribute1_1)::termexclimationpt_term_attribute642_1), (d' , (attribute1_2)::termexclimationpt_term_attribute642_2)-> true && eq_attribute(attribute1_1 , attribute1_2) && eq_termexclimationpt_term_attribute64((d,termexclimationpt_term_attribute642_1) , (d',termexclimationpt_term_attribute642_2))
   | _ -> false

and eq_termexiststerm_term_sortedvar62 = function 
   |(_,[]),(_,[])-> true
   | (d , (sortedvar1_1)::termexiststerm_term_sortedvar622_1), (d' , (sortedvar1_2)::termexiststerm_term_sortedvar622_2)-> true && eq_sortedvar(sortedvar1_1 , sortedvar1_2) && eq_termexiststerm_term_sortedvar62((d,termexiststerm_term_sortedvar622_1) , (d',termexiststerm_term_sortedvar622_2))
   | _ -> false

and eq_termforallterm_term_sortedvar60 = function 
   |(_,[]),(_,[])-> true
   | (d , (sortedvar1_1)::termforallterm_term_sortedvar602_1), (d' , (sortedvar1_2)::termforallterm_term_sortedvar602_2)-> true && eq_sortedvar(sortedvar1_1 , sortedvar1_2) && eq_termforallterm_term_sortedvar60((d,termforallterm_term_sortedvar602_1) , (d',termforallterm_term_sortedvar602_2))
   | _ -> false

and eq_termletterm_term_varbinding58 = function 
   |(_,[]),(_,[])-> true
   | (d , (varbinding1_1)::termletterm_term_varbinding582_1), (d' , (varbinding1_2)::termletterm_term_varbinding582_2)-> true && eq_varbinding(varbinding1_1 , varbinding1_2) && eq_termletterm_term_varbinding58((d,termletterm_term_varbinding582_1) , (d',termletterm_term_varbinding582_2))
   | _ -> false

and eq_termqualidterm_term_term56 = function 
   |(_,[]),(_,[])-> true
   | (d , (term1_1)::termqualidterm_term_term562_1), (d' , (term1_2)::termqualidterm_term_term562_2)-> true && eq_term(term1_1 , term1_2) && eq_termqualidterm_term_term56((d,termqualidterm_term_term562_1) , (d',termqualidterm_term_term562_2))
   | _ -> false

and eq_sortidsortmulti_sort_sort44 = function 
   |(_,[]),(_,[])-> true
   | (d , (sort1_1)::sortidsortmulti_sort_sort442_1), (d' , (sort1_2)::sortidsortmulti_sort_sort442_2)-> true && eq_sort(sort1_1 , sort1_2) && eq_sortidsortmulti_sort_sort44((d,sortidsortmulti_sort_sort442_1) , (d',sortidsortmulti_sort_sort442_2))
   | _ -> false

and eq_sexprinparen_sexpr_sexpr41 = function 
   |(_,[]),(_,[])-> true
   | (d , (sexpr1_1)::sexprinparen_sexpr_sexpr412_1), (d' , (sexpr1_2)::sexprinparen_sexpr_sexpr412_2)-> true && eq_sexpr(sexpr1_1 , sexpr1_2) && eq_sexprinparen_sexpr_sexpr41((d,sexprinparen_sexpr_sexpr412_1) , (d',sexprinparen_sexpr_sexpr412_2))
   | _ -> false

and eq_idunderscoresymnum_identifier_numeral33 = function 
   |(_,[]),(_,[])-> true
   | (d , (str1_1)::idunderscoresymnum_identifier_numeral332_1), (d' , (str1_2)::idunderscoresymnum_identifier_numeral332_2)-> true && str1_1 = str1_2 && eq_idunderscoresymnum_identifier_numeral33((d,idunderscoresymnum_identifier_numeral332_1) , (d',idunderscoresymnum_identifier_numeral332_2))
   | _ -> false

and eq_commands_commands_command30 = function 
   |(_,[]),(_,[])-> true
   | (d , (command1_1)::commands_commands_command302_1), (d' , (command1_2)::commands_commands_command302_2)-> true && eq_command(command1_1 , command1_2) && eq_commands_commands_command30((d,commands_commands_command302_1) , (d',commands_commands_command302_2))
   | _ -> false

and eq_commandgetvalue_command_term24 = function 
   |(_,[]),(_,[])-> true
   | (d , (term1_1)::commandgetvalue_command_term242_1), (d' , (term1_2)::commandgetvalue_command_term242_2)-> true && eq_term(term1_1 , term1_2) && eq_commandgetvalue_command_term24((d,commandgetvalue_command_term242_1) , (d',commandgetvalue_command_term242_2))
   | _ -> false

and eq_commanddefinefun_command_sortedvar15 = function 
   |(_,[]),(_,[])-> true
   | (d , (sortedvar1_1)::commanddefinefun_command_sortedvar152_1), (d' , (sortedvar1_2)::commanddefinefun_command_sortedvar152_2)-> true && eq_sortedvar(sortedvar1_1 , sortedvar1_2) && eq_commanddefinefun_command_sortedvar15((d,commanddefinefun_command_sortedvar152_1) , (d',commanddefinefun_command_sortedvar152_2))
   | _ -> false

and eq_commanddeclarefun_command_sort13 = function 
   |(_,[]),(_,[])-> true
   | (d , (sort1_1)::commanddeclarefun_command_sort132_1), (d' , (sort1_2)::commanddeclarefun_command_sort132_2)-> true && eq_sort(sort1_1 , sort1_2) && eq_commanddeclarefun_command_sort13((d,commanddeclarefun_command_sort132_1) , (d',commanddeclarefun_command_sort132_2))
   | _ -> false

and eq_commanddefinesort_command_symbol11 = function 
   |(_,[]),(_,[])-> true
   | (d , (symbol1_1)::commanddefinesort_command_symbol112_1), (d' , (symbol1_2)::commanddefinesort_command_symbol112_2)-> true && eq_symbol(symbol1_1 , symbol1_2) && eq_commanddefinesort_command_symbol11((d,commanddefinesort_command_symbol112_1) , (d',commanddefinesort_command_symbol112_2))
   | _ -> false

and eq_attributevalsexpr_attributevalue_sexpr5 = function 
   |(_,[]),(_,[])-> true
   | (d , (sexpr1_1)::attributevalsexpr_attributevalue_sexpr52_1), (d' , (sexpr1_2)::attributevalsexpr_attributevalue_sexpr52_2)-> true && eq_sexpr(sexpr1_1 , sexpr1_2) && eq_attributevalsexpr_attributevalue_sexpr5((d,attributevalsexpr_attributevalue_sexpr52_1) , (d',attributevalsexpr_attributevalue_sexpr52_2))
   | _ -> false
;;
let eq e = eq_commands e;;